# Generated by Django 3.2.6 on 2021-08-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile picture'),
            preserve_default=False,
        ),
    ]
