# Generated by Django 3.2.6 on 2021-08-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_contactinformation_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('job_description', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
