# Generated by Django 3.2.6 on 2021-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_previousemployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_university', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('description', models.TextField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
    ]
